#! python3

from re import compile as regcomp
from keyword import kwlist
from sys import argv

invars = {}
outvars = {}

with open('scriptconfig') as fh:
	for line in fh:
		key, sep, val = line.rstrip().partition('=')
		invars[key] = val

is_wellformed = regcomp(r'(?:[^\\\$\`]|\$(?:\{\w+}|\w+)|\\.)+').fullmatch
expand_vars = regcomp(r'\\(.)|\$(?:\{(\w+)\}|(\w+))').sub
escape_quotes = regcomp(r'[\\"]').sub

def expansion(match):
	subexp = match.group(1)
	if subexp is not None:
		return subexp
	subexp = match.group(2)
	if subexp is not None:
		return outvars.get(subexp, '')
	subexp = match.group(3)
	if subexp is not None:
		return outvars.get(subexp, '')
	return ''

changed = True
while changed:
	changed = False
	for key, val in invars.items():
		if is_wellformed(val):
			val = expand_vars(expansion, val)
			if outvars.get(key) != val:
				outvars[key] = val
				changed = True

print(f"#! {outvars['PYTHON3']} -O\n\nclass autoconf:")

for key in sorted(outvars):
	val = outvars[key]
	escaped_val = escape_quotes(r'\\\g<0>', val)
	while key in kwlist:
		key = 'ac_' + key
	print(f"\t{key} = \"{escaped_val}\"")

for filename in argv[1:]:
	print()
	with open(filename) as fh:
		print(fh.read(), end = '')
