#! /bin/sh

export PERLLIB=$HOME/fruitbak/lib
PATH=$HOME/fruitbak/bin:$PATH

set -ex

tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT INT HUP TERM QUIT

cd "$tmp"

hostdir=/media/wsl/MyBook/host

mkdir -p conf/host

cat >conf/global.pl <<EOT
our %conf;

\$conf{rootdir} = '$tmp';
\$conf{hostdir} = '$hostdir';

\$conf{pool} = ['filesystem', dir => '/media/wsl/MyBook/pool'];

1;
EOT

cat >conf/common.pl <<EOT
1;
EOT

for i in $(ssh root@rot 'cd /bak && ls -vd vms-*')
do
	for h in $(ssh root@rot "cd /bak/$i && ls -v")
	do
		rm -rf $hostdir/$h
	done
done

for i in $(ssh root@rot 'cd /bak && ls -vd vms-*') vms
do
	n=${i#*-}
	pids=
	for h in $(ssh root@rot "cd /bak/$i && ls -v")
	do
		mkdir -p $hostdir/$h
		cat >conf/host/$h.pl <<EOT
our %conf;

\$conf{host} = 'rot';
\$conf{user} = 'root';

\$conf{shares} = [
$(for s in $(ssh root@rot "cd /bak/$i/$h && echo */*")
do
	echo "	{name => \"$s\", path => \"/bak/$i/$h/$s\"},"
done)
];
EOT
		(
			fruitbak bu $h
			case $i in vms) ;; *)
				last=$(cd $hostdir/$h && ls -vd [0-9]* | tail -1)
				case $last in $n) ;; *)
					mv $hostdir/$h/$last $hostdir/$h/$n
				esac
			esac
		) &
		pids="$pids $!"
	done

	for p in $pids
	do
		wait $p
	done
done
