#! /bin/sh

export PERLLIB=$HOME/fruitbak/lib
PATH=$HOME/fruitbak/bin:$PATH

set -ex

tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT INT HUP TERM QUIT

cd "$tmp"

hostdir=/media/wsl/MyBook/host

mkdir -p conf/host

cat >conf/global.pl <<EOT
our %conf;

\$conf{rootdir} = '$tmp';
\$conf{hostdir} = '$hostdir';

\$conf{pool} = ['filesystem', dir => '/media/wsl/MyBook/pool'];

1;
EOT

cat >conf/common.pl <<EOT
1;
EOT

rm -rf $hostdir/rot
mkdir $hostdir/rot

for i in $(ssh root@rot 'cd /bak && ls -vd rot-*') rot
do
	h=${i%-*}
	n=${i#*-}

	cat >conf/host/rot.pl <<EOT
our %conf;

\$conf{host} = 'rot';
\$conf{user} = 'root';

\$conf{shares} = [
$(for s in $(ssh root@rot "cd /bak/$i && ls -v")
do
	echo "	{name => \"$s\", path => \"/bak/$i/$s\"},"
done)
];
EOT
	fruitbak bu rot
	case $i in rot) ;; *)
		last=$(cd $hostdir/$h && ls -vd [0-9]* | tail -1)
		case $last in $n) ;; *)
			mv $hostdir/$h/$last $hostdir/$h/$n
		esac
	esac
	export DEBUG=1
done
