#! /bin/sh

set -e

unset LANG
export PERLLIB=lib
PATH=bin:$PATH

rm -rf /dev/shm/host /dev/shm/pool
mkdir -p /dev/shm/host/pikachu /dev/shm/pool

set -x

rm -rf /var/tmp/afdrukken/extra
mkdir /var/tmp/afdrukken/extra
mknod /var/tmp/afdrukken/extra/pijp p
mknod /var/tmp/afdrukken/extra/devnull c 1 3 || :
ln -s doelwit /var/tmp/afdrukken/extra/symlinkje
date -R >/var/tmp/afdrukken/extra/foo
ln /var/tmp/afdrukken/extra/foo /var/tmp/afdrukken/extra/bar
uptime >/var/tmp/afdrukken/extra/あ
uname -a >/var/tmp/afdrukken/extra/'\	
'

date >/var/tmp/afdrukken/extra/xyzzy

fruitbak bu
fruitbak gc

for i in $(seq 10)
do
	#cat /var/tmp/afdrukken/great_ocean_road_shooped.xcf >>/var/tmp/afdrukken/extra/xyzzy
	#touch /var/tmp/afdrukken/extra/xyzzy
	date >> /var/tmp/afdrukken/extra/xyzzy

	fruitbak bu
	fruitbak gc
done

fruitbak scrub
